name: Semantic release
on:
  push:
    branches:
      - master
      - develop
jobs:
  semantic_release:
    name: Semantic release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Semantic release
        id: release
        uses: codfish/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: |
            [
              "master",
              {
                "name": "develop",
                "prerelease": true
              }
            ]
